# Generated by Django 4.2.5 on 2023-10-08 21:59

import apps.comentario.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0013_alter_publicacion_fecha_publicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comentario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateField(default=apps.comentario.models.get_fecha_actual),
        ),
        migrations.AddField(
            model_name='comentario',
            name='publicacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='publicacion.publicacion'),
            preserve_default=False,
        ),
    ]
