# Generated by Django 4.2.5 on 2023-09-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propietario', '0002_propietario_apellido_propietario_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='nombre',
        ),
    ]
