# Generated by Django 4.2.5 on 2023-09-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietario', '0003_remove_propietario_apellido_remove_propietario_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='apellido',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propietario',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
