# Generated by Django 4.2.5 on 2023-09-17 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='titulo',
        ),
    ]
