# Generated by Django 4.2.5 on 2023-09-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0002_remove_publicacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='descripcion',
            field=models.CharField(default='', max_length=255, verbose_name='Descripcion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(default='', max_length=100, verbose_name='Titulo'),
            preserve_default=False,
        ),
    ]
