# Generated by Django 4.2.5 on 2023-09-19 20:47

import apps.publicacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0003_publicacion_descripcion_publicacion_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateField(default=apps.publicacion.models.get_fecha_actual),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='ubicacion',
            field=models.CharField(default='', max_length=20, verbose_name='barrio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
    ]
