# Generated by Django 4.2.5 on 2023-09-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0004_publicacion_fecha_publicacion_publicacion_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='barrio',
            field=models.CharField(default='', max_length=50, verbose_name='barrio'),
            preserve_default=False,
        ),
    ]
