# Generated by Django 4.2.5 on 2023-09-30 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propietario', '0006_alter_propietario_options_alter_propietario_managers_and_more'),
        ('publicacion', '0006_publicacion_propietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='barrio',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('alquilado', 'Alquilado')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='ubicacion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propietario.propietario'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
