# Generated by Django 4.2.5 on 2023-10-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0007_remove_publicacion_barrio_publicacion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.CharField(default='30/09/2023', max_length=10),
        ),
    ]
