# Generated by Django 4.2.5 on 2023-10-01 01:56

import apps.publicacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0008_alter_publicacion_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateField(default=apps.publicacion.models.get_fecha_actual),
        ),
    ]
