# Generated by Django 4.2.5 on 2023-09-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilino', '0003_alter_inquilino_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilino',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
