# Generated by Django 4.2.5 on 2023-09-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilino', '0004_alter_inquilino_apellido_alter_inquilino_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquilino',
            name='password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='apellido',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
