# Generated by Django 4.2.5 on 2023-09-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inquilino', '0010_remove_inquilino_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquilino',
            name='groups',
            field=models.ManyToManyField(related_name='inquilinos', to='auth.group'),
        ),
        migrations.AddField(
            model_name='inquilino',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inquilino',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquilino',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='inquilino',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='inquilino',
            name='user_permissions',
            field=models.ManyToManyField(related_name='inquilinos_user_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
