# Generated by Django 4.2.5 on 2023-09-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inquilino', '0011_inquilino_groups_inquilino_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilino',
            name='groups',
            field=models.ManyToManyField(related_name='inquilino_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='user_permissions',
            field=models.ManyToManyField(related_name='inquilino_user_permissions', to='auth.permission'),
        ),
    ]
