# Generated by Django 4.2.5 on 2023-09-28 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquilino', '0016_inquilino_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquilino',
            name='user',
        ),
    ]
